export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// REFRESH TOKEN
export const REFRESH_TOKEN = "REFRESH_TOKEN";

// PROFILE
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const SEND_REQUEST = "SEND_REQUEST";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const GET_REQUESTS = "GET_REQUESTS";
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_INVITATIONS = "GET_INVITATIONS";
export const ACCEPT_INVITATIONS = "ACCEPT_INVITATIONS";

// posts
export const GET_POSTS = "GET_POSTS";
export const POSTS_ERROR = "POSTS_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
